name: DP-SimpleShop
version: 1.0.2.11
main: com.darksoldier1404.dss.SimpleShop
api-version: 1.13
authors: [ DEAD_POOLIO_ ]
depend:
  - DPP-Core
  - Essentials
commands:
  상점:
    aliases: [shop, dshop, dss]
